<?php
$d=$spec['discovery'];$issuer=$spec['issuer'];$base=$issuer.'/protocol/openid-connect';
$code=function(string $id,string $text)use($e){echo '<div class="api-code"><button type="button" data-api-copy="'.$e($id).'" aria-label="复制 '.$e($id).'">复制</button><pre><code id="'.$e($id).'">'.$e($text).'</code></pre></div>';};
?>
<link rel="stylesheet" href="/assets/api-docs.f961a9e3544f9105.css"><script src="/assets/api-docs.449c73ff97380767.js" defer></script>
<div class="api-intro"><span class="api-tag">开发者文档 · OIDC</span><h1>接入 52okp 统一登录</h1><p>让你的业务网站使用同一套账号。账号密码与微信扫码在中枢完成，业务网站获取经过验证的用户身份。</p><div class="actions"><a class="button" href="#quickstart">开始接入</a><a href="/api/spec">JSON 接口说明 ↗</a><a href="<?= $e($spec['discovery_url']) ?>">OIDC 发现配置 ↗</a></div></div>
<div class="api-docs"><nav class="api-toc" aria-label="API 文档目录"><?php foreach(['quickstart'=>'接入准备','endpoints'=>'接口地址','authorize'=>'发起登录','callback'=>'回调与换码','userinfo'=>'获取用户资料','refresh'=>'刷新与撤销','logout'=>'退出登录','errors'=>'错误排查','checklist'=>'联调检查'] as $id=>$label): ?><a href="#<?= $id ?>"><?= $label ?></a><?php endforeach ?></nav><div class="api-body">
<p class="muted api-copy-status" data-api-copy-status role="status">示例中的客户端、域名和令牌均为占位值，请替换为你自己的配置。</p>
<section class="card" id="quickstart"><h2>01 · 接入准备</h2><ol><li>管理员进入 <a href="/admin?section=clients">后台 → 用户接入</a>，为每个业务项目创建独立应用。</li><li>填写应用 ID、名称和登录回调，例如 <code>https://your-app.example/auth/callback</code>。回调必须精确匹配已登记的完整 HTTPS 地址，不支持通配符。</li><li>有后端的网站选择“服务端应用（密钥）”。保存后妥善保管只展示一次的 <code>client_secret</code>，仅放在业务网站服务器环境变量中。</li><li>在业务项目使用 OIDC 客户端库，启用授权码流程、PKCE S256、state 和 nonce 校验。</li></ol>
<?php $code('connection-config','OIDC_ISSUER='.$issuer."\nOIDC_CLIENT_ID=your-client-id\nOIDC_CLIENT_SECRET=<仅保存在业务网站服务器>\nOIDC_REDIRECT_URI=https://your-app.example/auth/callback\nOIDC_SCOPES=openid profile email\nOIDC_PKCE_METHOD=S256"); ?>
<p>登录流程：业务网站 → 中枢登录 / 扫码确认 → 业务网站回调 → 后端兑换令牌并验证 → 建立业务网站自己的会话。</p><p class="notice">业务网站无需单独接微信 API。微信扫码由中枢授权页面统一处理。不要使用普通 <code>/login</code> 页面代替 OIDC 授权端点，也不要直接调用中枢内部的微信票据接口。</p></section>
<section class="card" id="endpoints"><h2>02 · 接口地址</h2><p>Issuer：<code><?= $e($issuer) ?></code>。地址随本站配置生成，优先使用发现配置中的端点。</p><div class="table"><table><thead><tr><th>接口 / 方法</th><th>地址与认证</th></tr></thead><tbody><?php foreach($spec['endpoints'] as $endpoint): ?><tr><td><strong><?= $e($endpoint['name']) ?></strong><small><?= $e($endpoint['method']) ?></small></td><td><code><?= $e($endpoint['url']) ?></code><small><?= $e($endpoint['auth']) ?></small></td></tr><?php endforeach ?></tbody></table></div><p>Token、自省、撤销接口使用表单编码 <code>application/x-www-form-urlencoded</code>。不能发送 JSON，也不要重复提交同名参数。</p></section>
<section class="card" id="authorize"><h2>03 · 发起登录</h2><p>由业务网站生成新的授权请求，再让浏览器跳转到 <code><?= $e($d['authorization_endpoint']) ?></code>。</p><div class="table"><table><tr><th>参数</th><th>要求</th></tr><?php foreach(['response_type'=>'固定为 code','client_id'=>'后台登记的应用 ID','redirect_uri'=>'与登记值完全一致的登录回调地址','scope'=>'必须包含 openid；资料按需添加 profile 和 email，以空格分隔','state'=>'每次独立随机生成，8～255 字符；保存在会话中防止请求伪造','nonce'=>'与 state 分开随机生成，8～255 字符；用于验证 ID Token','code_challenge'=>'BASE64URL(SHA256(code_verifier))，无 = 填充，43 字符','code_challenge_method'=>'固定为 S256；服务端应用同样必填'] as $key=>$value): ?><tr><td><code><?= $e($key) ?></code></td><td><?= $e($value) ?></td></tr><?php endforeach ?></table></div>
<h3>PHP 发起请求示例</h3><p>这段代码放在业务网站，不放在中枢。它只演示发起流程；回调验证见下一节。</p>
<?php $code('php-authorize',"<?php\nsession_start();\n\$b64 = fn(\$v) => rtrim(strtr(base64_encode(\$v), '+/', '-_'), '=');\n\$state = \$b64(random_bytes(32));\n\$nonce = \$b64(random_bytes(32));\n\$verifier = \$b64(random_bytes(32));\n\$redirect = 'https://your-app.example/auth/callback';\n\$_SESSION['oidc_requests'][\$state] = [\n    'nonce' => \$nonce, 'verifier' => \$verifier,\n    'redirect_uri' => \$redirect, 'created_at' => time(),\n];\n\$query = http_build_query([\n    'response_type' => 'code',\n    'client_id' => getenv('OIDC_CLIENT_ID'),\n    'redirect_uri' => \$redirect,\n    'scope' => 'openid profile email',\n    'state' => \$state, 'nonce' => \$nonce,\n    'code_challenge' => \$b64(hash('sha256', \$verifier, true)),\n    'code_challenge_method' => 'S256',\n], '', '&', PHP_QUERY_RFC3986);\nsession_write_close();\nheader('Location: '.".var_export($d['authorization_endpoint'].'?',true).".\$query);\nexit;" ); ?>
<p>每次授权都需要主动验证身份，不提供静默 SSO；<code>prompt=none</code> 不支持。已有中枢登录 Cookie 也不会跳过此步骤。</p></section>
<section class="card" id="callback"><h2>04 · 处理回调并兑换令牌</h2><p>成功回调携带 <code>code</code> 和原 <code>state</code>；取消时携带 <code>error=access_denied</code> 与原 <code>state</code>。</p><ol><li>先核对 state 对应本地会话中的未过期请求（建议不超过 5 分钟），拒绝缺失或不匹配值；读取后消耗该请求，避免重放。出错回调也必须核对 state。</li><li>若有 error，结束本次登录；否则后端使用 code、原 redirect_uri 和原 code_verifier 换码。授权码有效期 60 秒，只能兑换一次。</li><li>验证 ID Token 后，使用 <code>(iss, sub)</code> 查找或创建业务账号，再更新业务网站的会话 ID。</li></ol>
<h3>服务端换码示例（HTTP Basic）</h3><?php $code('token-request',"curl --request POST '".$d['token_endpoint']."' \\\n  --user 'your-client-id:YOUR_CLIENT_SECRET' \\\n  --header 'Content-Type: application/x-www-form-urlencoded' \\\n  --data-urlencode 'grant_type=authorization_code' \\\n  --data-urlencode 'code=CODE_FROM_CALLBACK' \\\n  --data-urlencode 'redirect_uri=https://your-app.example/auth/callback' \\\n  --data-urlencode 'code_verifier=ORIGINAL_CODE_VERIFIER'"); ?>
<p>也可不使用 Basic，改为在表单中提交 <code>client_id</code> 和 <code>client_secret</code>，两种认证方式不能混用。公共客户端只提交 client_id，不提交 secret；同样必须使用 PKCE。客户端 ID 含特殊字符时，Basic 认证应按 OAuth 规则编码，优先交给客户端库处理。</p>
<?php $code('token-response',json_encode(['token_type'=>'Bearer','expires_in'=>300,'access_token'=>'<ACCESS_TOKEN>','refresh_token'=>'<REFRESH_TOKEN>','id_token'=>'<ID_TOKEN>','scope'=>'openid profile email'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)); ?>
<h3>ID Token 验证要求</h3><ul><li>从可信发现配置的 JWKS 地址按 kid 选择公钥，只允许 RS256 并验证签名。</li><li>校验 iss 等于本站 Issuer、aud 包含自己的 client_id，检查 exp、iat、nbf 时间条件。</li><li>nonce 必须等于本次会话保存的值；at_hash 必须匹配本次 access_token。</li><li>读取 UserInfo 后，再确认它的 sub 与已验证 ID Token 的 sub 一致。</li></ul><p class="notice">不要只解码 JWT 就相信用户身份，也不要用昵称、邮箱或微信 OpenID 作为跨项目的唯一账号标识。统一使用已验证的 Issuer + sub。</p></section>
<section class="card" id="userinfo"><h2>05 · 获取用户资料</h2><?php $code('userinfo-request',"curl '".$d['userinfo_endpoint']."' \\\n  --header 'Authorization: Bearer YOUR_ACCESS_TOKEN'"); $code('userinfo-response',json_encode(['sub'=>'00000000-0000-4000-8000-000000000001','name'=>'示例用户','preferred_username'=>'example-user','email'=>'user@example.com','email_verified'=>true],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)); ?>
<div class="table"><table><tr><th>Scope</th><th>返回字段</th></tr><tr><td>openid</td><td>sub</td></tr><tr><td>profile</td><td>name、preferred_username</td></tr><tr><td>email</td><td>已设置邮箱时返回 email、email_verified；邮箱可能不存在</td></tr></table></div><p>微信登录用户可能没有邮箱。业务项目需允许邮箱为空；如确需邮箱，可引导用户到中枢账号页绑定。</p></section>
<section class="card" id="refresh"><h2>06 · 刷新、自省与撤销</h2><p>访问令牌与 ID Token 通常有效 5 分钟。刷新令牌单次轮换，最长不超过最初身份验证后的 8 小时。</p>
<?php $code('refresh-request',"curl --request POST '".$d['token_endpoint']."' \\\n  --user 'your-client-id:YOUR_CLIENT_SECRET' \\\n  --data-urlencode 'grant_type=refresh_token' \\\n  --data-urlencode 'refresh_token=CURRENT_REFRESH_TOKEN'"); ?>
<p>成功后原子保存新的令牌，下一次只能使用新的 refresh_token。同一会话的刷新必须串行处理；重用旧刷新令牌会撤销该用户在当前应用的凭证，需重新登录。</p>
<?php $code('introspect-request',"curl --request POST '".$d['introspection_endpoint']."' \\\n  --user 'your-client-id:YOUR_CLIENT_SECRET' \\\n  --data-urlencode 'token=TOKEN_TO_CHECK'"); $code('introspect-response',json_encode(['active'=>true,'client_id'=>'your-client-id','sub'=>'00000000-0000-4000-8000-000000000001','iss'=>$issuer,'exp'=>2000000000,'scope'=>'openid profile email','token_type'=>'Bearer'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)); ?>
<p>自省仅限保密客户端查询自己的令牌；无效、过期、已撤销或不属于该应用的令牌返回 <code>{"active":false}</code>。</p>
<?php $code('revoke-request',"curl --request POST '".$d['revocation_endpoint']."' \\\n  --user 'your-client-id:YOUR_CLIENT_SECRET' \\\n  --data-urlencode 'token=TOKEN_TO_REVOKE'"); ?>
<p>撤销成功返回 HTTP 200、空响应。撤销访问令牌或刷新令牌会使关联的访问令牌与刷新令牌失效；未知或非本应用令牌也可返回空响应，不用于判断令牌归属。</p></section>
<section class="card" id="logout"><h2>07 · 退出登录</h2><p>业务网站先销毁自己的会话，再让浏览器跳转到中枢退出页。退出中枢需要用户确认，不是直接用 API 无提示退出。</p>
<?php $code('logout-request',$d['end_session_endpoint']."\n  ?id_token_hint=<此前已验证的 ID_TOKEN>\n  &post_logout_redirect_uri=<已登记的退出回调，URL 编码>\n  &state=<退出请求的独立随机值>"); ?>
<p>上面分行仅为阅读方便，实际使用 URL 构造工具编码成完整地址。业务网站在退出回调校验 state；不需要回跳时可只导航到退出端点。中枢退出会撤销该账号凭证，但不会主动删除其他网站的本地 Session。</p><p>需要及时感知撤销时，业务后端使用自省或 UserInfo，并设置本地会话有效期。单纯离线验 JWT 签名可能在 exp 前继续接受旧令牌。</p></section>
<section class="card" id="errors"><h2>08 · 常见接入问题</h2><div class="table"><table><tr><th>现象</th><th>检查项</th></tr><tr><td>回调地址不匹配</td><td>检查 HTTPS、路径、结尾斜杠和查询参数；授权与换码必须使用同一个已登记地址。</td></tr><tr><td>invalid_client / 401</td><td>应用是否启用、ID 与密钥是否正确；Basic 与表单 secret 不要同时发送。</td></tr><tr><td>invalid_grant</td><td>code 是否超过 60 秒或已兑换；PKCE verifier 是否来自原请求；refresh_token 是否已轮换、过期或撤销。</td></tr><tr><td>state / nonce 校验失败</td><td>检查业务网站 Session/Cookie 是否保留，避免多个标签页覆盖同一请求数据，不要跳过验证。</td></tr><tr><td>浏览器跨域失败</td><td>当前不开放通用 CORS。用业务后端换码与获取资料；公共客户端不等于支持浏览器跨域换码。</td></tr><tr><td>429</td><td>按 Retry-After 等待；令牌端点对来源 IP 限流，不要反复并发刷新。</td></tr><tr><td>缺少邮箱</td><td>请求 email scope，并允许尚未绑定邮箱的账号正常存在。</td></tr></table></div><p>OAuth 令牌错误通常返回 <code>error</code>、<code>error_description</code> 等字段；应用校验错误可能返回 <code>error</code> 和 <code>message</code>。始终先检查 HTTP 状态，不把错误正文当成功结果。</p><p>不支持密码 grant、client_credentials、implicit、SAML 和 Keycloak Admin API。</p></section>
<section class="card" id="checklist"><h2>09 · 联调检查</h2><ul><li>同一已绑定账号使用密码登录或微信扫码，均能回到正确业务网站并映射到同一个 sub。</li><li>用户取消登录时正确展示取消状态，不创建本地登录会话。</li><li>错误 state、错误 PKCE、重复使用 code 均被拒绝。</li><li>刷新后保存新 refresh_token；过期或撤销后重新发起登录。</li><li>退出后销毁业务网站会话，退出回调 state 得到验证。</li><li>client_secret、access_token 和 refresh_token 仅保存在服务端，不进入前端源码、公开日志或地址栏。</li></ul><p>把本页或 <a href="/api/spec">JSON 接口说明</a>提供给其他项目即可开始接入；实际 client_id、密钥与回调需为每个项目分别配置。</p></section>
</div></div>
