<?php
$isAdmin=isset($adminSection);
$isAuth=!$isAdmin&&in_array($template,['login','email-form','otp','totp','recovery','error','continue','logout'],true);
$navigation=$isAdmin?[
 ['users','/admin?section=users','users','用户管理'],['clients','/admin?section=clients','grid','应用接入'],['settings','/admin?section=settings','settings','服务配置'],['updates','/admin/updates','download','程序更新']
]:[
 ['home','/','home','账号首页'],['account',$user?'/account':'/login','user','我的账号'],['api','/api','code','接入文档'],['privacy','/privacy','shield','账号与隐私']
];
?><!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f5f6f8"><title><?= $e($title??'账号中心') ?> · 52okp</title><link rel="stylesheet" href="/assets/<?= $e($assets['app.css']) ?>"><script src="/assets/<?= $e($assets['app.js']) ?>" defer></script></head>
<body class="page-<?= $e($isAdmin?'admin':$template) ?><?= $isAuth?' auth-page':'' ?>"><a class="skip-link" href="#main-content">跳到主要内容</a>
<?php if(!$isAuth): ?><div class="app-shell<?= $isAdmin?' admin-shell':'' ?>"><aside class="sidebar<?= $isAdmin?' admin-sidebar':'' ?>"><a class="sidebar-title" href="<?= $isAdmin?'/admin':'/' ?>"><span class="rail-home"><?= $icon($isAdmin?'settings':'home') ?></span><?= $isAdmin?'管理工作台':'52okp 统一账号' ?></a><p class="nav-caption"><?= $isAdmin?'管理':'账号服务' ?></p><nav class="side-menu<?= $isAdmin?' admin-menu':'' ?>" aria-label="<?= $isAdmin?'后台管理导航':'账号服务导航' ?>"><?php foreach($navigation as [$key,$href,$glyph,$label]): ?><a href="<?= $e($href) ?>" <?= ($isAdmin?$adminSection:$template)===$key?'aria-current="page"':'' ?>><?= $icon($glyph) ?><span><?= $e($label) ?></span></a><?php endforeach ?><?php if($user) require $app->config->path('resources/views/session-links.php'); ?></nav><div class="sidebar-bottom"><a href="https://hao.52okp.com/" target="_blank" rel="noopener noreferrer"><?= $icon('external') ?>52okp 导航</a><small>一个账号，连接你的应用。</small></div></aside><div class="workspace"><main id="main-content" class="<?= $isAdmin?'admin-workspace':'' ?>"><?php if($flash): ?><p class="notice" role="status"><?= $e($flash) ?></p><?php endif ?><?= $content ?></main>
<?php else: ?><main id="main-content" class="auth-main"><div class="auth-frame"><aside class="auth-intro"><span class="hero-tag"><?= $icon('shield') ?>52okp 统一账号</span><h2>连接应用，<br>从一个账号开始。</h2><p>在这里管理你的身份，<br>让每一次登录简单、有序。</p><div class="auth-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="art-node art-user"><?= $icon('user') ?></span><span class="art-node art-app"><?= $icon('grid') ?></span><span class="art-node art-key"><?= $icon('key') ?></span><span class="art-node art-shield"><?= $icon('shield') ?></span></div><small><?= $icon('check') ?>每次授权，由你确认</small></aside><div class="auth-content"><?php if($flash): ?><p class="notice" role="status"><?= $e($flash) ?></p><?php endif ?><?= $content ?></div></div></main><?php endif ?>
<footer class="site-footer"><span>© <?= date('Y') ?> 52okp · 统一账号中心</span><div><a href="/api">API 接入文档</a><a href="/privacy">账号与隐私说明</a></div><?php if($isAuth&&$user): ?><nav class="auth-session" aria-label="账号操作"><?php require $app->config->path('resources/views/session-links.php'); ?></nav><?php endif ?></footer><?php if(!$isAuth): ?></div></div><?php endif ?></body></html>
