<?php
declare(strict_types=1);
// This suite only runs against a dedicated *_test database. It does not delete existing accounts.
$a=require dirname(__DIR__).'/bootstrap.php';
if(!str_ends_with($a->config->values['db']['database'],'_test')||$a->config->production())throw new RuntimeException('Tests require development and a dedicated *_test database');
use Okp\{Crypto,Problem,Wechat,LoginRequests};
use Slim\Psr7\Factory\ServerRequestFactory;
$passed=0;
function ok(bool $condition,string $name):void{global $passed;if(!$condition)throw new RuntimeException('FAIL: '.$name);$passed++;echo "PASS $name\n";}
function rejects(callable $f,string $name):void{try{$f();}catch(Throwable $e){ok(true,$name);return;}ok(false,$name);}
function req(string $method,string $path,array $data=[],array $query=[]){$r=(new ServerRequestFactory())->createServerRequest($method,'http://127.0.0.1:8808'.$path,['REMOTE_ADDR'=>'127.0.0.1'])->withQueryParams($query);return $r->withHeader('Content-Type','application/x-www-form-urlencoded')->withParsedBody($data);}
function issued($a,array $u,string $client,string $secret,string $scope='openid profile email'):array{$verifier=Crypto::b64(random_bytes(48));$q=['client_id'=>$client,'redirect_uri'=>'https://example.test/callback','response_type'=>'code','scope'=>$scope,'state'=>Crypto::random(16),'nonce'=>Crypto::random(16),'code_challenge'=>Crypto::b64(hash('sha256',$verifier,true)),'code_challenge_method'=>'S256'];$r=req('GET','/auth',[],$q);$a->oauth()->validate($r);$response=$a->oauth()->complete($q,$u['id'],$r);parse_str(parse_url($response->getHeaderLine('Location'),PHP_URL_QUERY),$parts);return ['data'=>['grant_type'=>'authorization_code','client_id'=>$client,'client_secret'=>$secret,'code'=>$parts['code'],'redirect_uri'=>$q['redirect_uri'],'code_verifier'=>$verifier],'query'=>$q];}
function exchange($a,array $data):array{$r=$a->oauth()->token(req('POST','/token',$data));return ['status'=>$r->getStatusCode(),'body'=>json_decode((string)$r->getBody(),true)];}
$tag=Crypto::random(6);$u=$a->users->create('test-'.$tag.'@example.test','Valid-Test-Password42','测试用户');$v=$a->users->create('other-'.$tag.'@example.test','Valid-Test-Password42','另一用户');$client='test-'.$tag;$secret=Crypto::random();$a->db->run('INSERT INTO clients(id,name,secret_hash,confidential,redirect_uris,logout_uris,created_at) VALUES(?,?,?,1,?,?,?)',[$client,'测试应用',password_hash($secret,PASSWORD_BCRYPT),json_encode(['https://example.test/callback']),json_encode(['https://example.test/logout']),time()]);
ok(str_starts_with($a->db->one('SELECT VERSION() AS v')['v'],'5.7.'),'real MySQL 5.7 connection');
ok($a->users->authenticate($u['email'],'Valid-Test-Password42','test-'.$tag)['id']===$u['id'],'password authentication');ok($a->users->authenticate($u['email'],'invalid','test-'.$tag)===null,'wrong password rejected');
$flow=issued($a,$u,$client,$secret);$bad=$flow['query'];$bad['redirect_uri']='https://evil.example/callback';rejects(fn()=>$a->oauth()->validate(req('GET','/auth',[],$bad)),'exact redirect required');$bad=$flow['query'];$bad['code_challenge_method']='plain';rejects(fn()=>$a->oauth()->validate(req('GET','/auth',[],$bad)),'plain PKCE rejected');$bad=$flow['query'];$bad['prompt']='none';rejects(fn()=>$a->oauth()->validate(req('GET','/auth',[],$bad)),'silent login rejected');
$wrong=$flow['data'];$wrong['code_verifier']=str_repeat('a',64);ok(exchange($a,$wrong)['status']>=400,'wrong PKCE verifier rejected');$wrong=$flow['data'];$wrong['client_secret']='wrong';ok(exchange($a,$wrong)['status']>=400,'wrong client secret rejected');
$result=exchange($a,$flow['data']);ok($result['status']===200,'authorization code exchanged');$tokens=$result['body'];ok(isset($tokens['access_token'],$tokens['refresh_token'],$tokens['id_token']),'access refresh ID tokens returned');
$id=$a->oauth()->jwt->verify($tokens['id_token'],'JWT');ok($id->claims()->get('nonce')===$flow['query']['nonce'],'ID token nonce preserved');ok($id->claims()->get('sub')===$u['id'],'stable subject');ok($id->claims()->get('at_hash')===Crypto::b64(substr(hash('sha256',$tokens['access_token'],true),0,16)),'ID token at_hash matches exact access token');ok($id->claims()->get('email_verified')===true,'verified email claim');
$bearer=req('GET','/userinfo')->withHeader('Authorization','Bearer '.$tokens['access_token']);ok($a->oauth()->userinfo($bearer)['sub']===$u['id'],'signed access token userinfo');ok(exchange($a,$flow['data'])['status']>=400,'code single use');
$introspection=['client_id'=>$client,'client_secret'=>$secret,'token'=>$tokens['access_token']];ok($a->oauth()->introspect(req('POST','/introspect',$introspection))['active'],'authenticated introspection');$wrong=$introspection;$wrong['client_secret']='wrong';rejects(fn()=>$a->oauth()->introspect(req('POST','/introspect',$wrong)),'introspection requires client authentication');
$refresh=['grant_type'=>'refresh_token','client_id'=>$client,'client_secret'=>$secret,'refresh_token'=>$tokens['refresh_token']];$rotated=exchange($a,$refresh);ok($rotated['status']===200,'refresh rotation succeeds');ok($rotated['body']['refresh_token']!==$tokens['refresh_token'],'refresh token changed');ok(exchange($a,$refresh)['status']>=400,'refresh reuse rejected');$r=req('GET','/userinfo')->withHeader('Authorization','Bearer '.$rotated['body']['access_token']);rejects(fn()=>$a->oauth()->userinfo($r),'refresh reuse revokes newly issued access token');
$flow=issued($a,$u,$client,$secret,'openid');$limited=exchange($a,$flow['data'])['body'];$info=$a->oauth()->userinfo(req('GET','/userinfo')->withHeader('Authorization','Bearer '.$limited['access_token']));ok(array_keys($info)===['sub'],'scope filtering prevents email/profile disclosure');
$jti=$a->oauth()->jwt->verify($limited['access_token'])->claims()->get('jti');$a->db->run('UPDATE access_tokens SET expires_at=? WHERE id=?',[time()-1,$jti]);$active=$a->oauth()->introspect(req('POST','/introspect',['client_id'=>$client,'client_secret'=>$secret,'token'=>$limited['refresh_token']]));ok($active['active'],'refresh remains active after access expiry');
$forged=explode('.',$limited['access_token']);$payload=json_decode(base64_decode(strtr($forged[1],'-_','+/')),true);$payload['sub']=$v['id'];$forged[1]=Crypto::b64(json_encode($payload));rejects(fn()=>$a->oauth()->jwt->verify(implode('.',$forged)),'tampered JWT rejected');
$a->db->transaction(fn()=>$a->users->revokeSessions($u['id']));rejects(fn()=>$a->oauth()->userinfo(req('GET','/userinfo')->withHeader('Authorization','Bearer '.$limited['access_token'])),'session version invalidates access tokens');
$flow=issued($a,$u,$client,$secret);$a->db->run('UPDATE users SET enabled=0 WHERE id=?',[$u['id']]);ok(exchange($a,$flow['data'])['status']>=400,'disabled account cannot exchange code');$a->db->run('UPDATE users SET enabled=1 WHERE id=?',[$u['id']]);
$rate='test-rate-'.$tag;ok($a->rate->allow($rate,2,60),'rate first request');ok($a->rate->allow($rate,2,60),'rate second request');ok(!$a->rate->allow($rate,2,60),'rate excess rejected');
$binding=Crypto::random();$codeId=Crypto::random(16);$code='123456';$a->db->run('INSERT INTO email_codes(id,purpose,email,browser_hash,code_hash,expires_at) VALUES(?,?,?,?,?,?)',[$codeId,'register',$u['email'],$binding,$a->crypto->hash($codeId.':'.$code),time()+300]);ok(!$a->emails->consume($codeId,'register',$u['email'],'wrong',$code),'email code browser bound');ok(!$a->emails->consume($codeId,'register',$u['email'],$binding,'000000'),'wrong email code rejected');ok((int)$a->db->one('SELECT attempts FROM email_codes WHERE id=?',[$codeId])['attempts']===1,'failed email attempt persists');ok($a->emails->consume($codeId,'register',$u['email'],$binding,$code),'correct email code consumed');ok(!$a->emails->consume($codeId,'register',$u['email'],$binding,$code),'email code single use');
$totp=\OTPHP\TOTP::generate(new Okp\OAuth\Clock());$recovery=Crypto::random(8);$a->db->run('UPDATE users SET totp_secret=?,recovery_hashes=? WHERE id=?',[$a->crypto->encrypt($totp->getSecret()),json_encode([$a->crypto->hash($recovery)]),$u['id']]);$otp=$totp->now();ok($a->users->verifyTotp($u['id'],$otp,'otp-'.$tag),'TOTP accepted');ok(!$a->users->verifyTotp($u['id'],$otp,'otp-'.$tag),'TOTP replay rejected');ok($a->users->verifyTotp($u['id'],$recovery,'otp-'.$tag),'recovery code accepted');ok(!$a->users->verifyTotp($u['id'],$recovery,'otp-'.$tag),'recovery code single use');
$old=$a->settings->get('wechat');$a->settings->put('wechat',['enabled'=>true,'app_id'=>'wx4ec45155a93041cc','secret'=>'fixture-'.$tag,'page'=>'pages/account-confirm/index','env'=>'release']);$calls=[];$wx=new Wechat($a->settings,$a->db,function($path,$body)use(&$calls,$tag){$calls[]=$path;if(str_starts_with($path,'/sns/'))return ['body'=>json_encode(['openid'=>'openid-'.$tag]),'status'=>200];if(str_contains($path,'stable_token'))return ['body'=>json_encode(['access_token'=>'fixture-token','expires_in'=>7200]),'status'=>200];return ['body'=>base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aU1kAAAAASUVORK5CYII='),'status'=>200];});$tickets=new LoginRequests($a->db,$a->crypto,$a->rate,$wx,$a->users);
try{$created=$tickets->create($binding,['return'=>'/account'],'测试站点','qr-'.$tag);$ticket=$created['ticket']['id'];$details=$tickets->details($ticket,'qr-'.$tag);ok($details['expiresAt']>time()*1000&&$details['intent']==='LOGIN','published mini-program request contract');rejects(fn()=>$tickets->qrcode($ticket,'wrong'),'QR key required');$one=$tickets->qrcode($ticket,$created['key']);$two=$tickets->qrcode($ticket,$created['key']);ok($one===$two&&count($calls)===2,'QR image cached, stable_token fetched once');rejects(fn()=>$tickets->confirm(['ticket'=>$ticket,'code'=>'fixture','accepted'=>false,'decision'=>'confirm'],'qr-'.$tag),'confirmation requires consent');$tickets->confirm(['ticket'=>$ticket,'code'=>'fixture','accepted'=>true,'decision'=>'confirm'],'qr-'.$tag);ok($tickets->status($ticket,$created['key'])['state']==='CONFIRMED','mini-program confirmation updates state');rejects(fn()=>$tickets->consume($ticket,'wrong'),'QR browser binding enforced');$result=$tickets->consume($ticket,$binding);ok($result['user']['id']!=='','WeChat account initialized');rejects(fn()=>$tickets->consume($ticket,$binding),'QR confirmation single use');rejects(fn()=>$a->users->fromWechat('wx4ec45155a93041cc','openid-'.$tag,$v['id']),'no automatic WeChat account merge');$next=$tickets->create($binding,[],'测试站点','qr-'.$tag);$a->db->run('UPDATE login_requests SET expires_at=? WHERE id=?',[time()-1,$next['ticket']['id']]);rejects(fn()=>$tickets->consume($next['ticket']['id'],$binding),'expired QR rejected');ok($tickets->bound($next['ticket']['id'],$binding,false,true)['id']===$next['ticket']['id'],'expired request can be refreshed by original browser');$link=$tickets->create($binding,['target_version'=>(int)$v['session_version']],'绑定测试','qr-'.$tag,'LINK',$v['id']);$tickets->confirm(['ticket'=>$link['ticket']['id'],'code'=>'fixture','accepted'=>true,'decision'=>'confirm'],'qr-'.$tag);$a->db->transaction(fn()=>$a->users->revokeSessions($v['id']));rejects(fn()=>$tickets->consume($link['ticket']['id'],$binding),'revoked session cannot complete old WeChat binding');
$cancel=$tickets->create($binding,[],'取消测试','qr-'.$tag);$tickets->confirm(['ticket'=>$cancel['ticket']['id'],'code'=>'fixture','accepted'=>false,'decision'=>'cancel'],'qr-'.$tag);ok($tickets->status($cancel['ticket']['id'],$cancel['key'])['state']==='CANCELLED','mini-program cancellation supported');rejects(fn()=>$tickets->consume($cancel['ticket']['id'],$binding),'cancelled QR cannot sign in');}
finally{$a->settings->put('wechat',$old);}
echo "Completed: $passed assertions.\n";

