<?php
declare(strict_types=1);
require dirname(__DIR__).'/vendor/autoload.php';
use Okp\Update\{Engine,Package,Remote};
$source=dirname(__DIR__);$application=require $source.'/bootstrap.php';if($application->config->production()||!str_ends_with($application->config->values['db']['database'],'_test'))throw new RuntimeException('Updater tests require an isolated development *_test database');$fixture=$argv[1]??'';if(!is_file($fixture.'/update-manifest.json'))throw new RuntimeException('Pass an isolated fixture build directory');
$workspace=dirname($source).'/.local/update-tests-'.bin2hex(random_bytes(5));mkdir($workspace,0700,true);$count=0;
function assertUpdate(bool $condition,string $message):void{global $count;if(!$condition)throw new RuntimeException('FAIL '.$message);$count++;echo "PASS $message\n";}
function denied(callable $fn,string $message):void{try{$fn();}catch(Throwable){assertUpdate(true,$message);return;}assertUpdate(false,$message);}
function makeRoot(string $name):string {global $source,$workspace;$root=$workspace.'/'.$name;mkdir($root,0700);foreach(Package::inventory($source) as $file=>$hash){$to=$root.'/'.$file;if(!is_dir(dirname($to)))mkdir(dirname($to),0755,true);copy($source.'/'.$file,$to);}mkdir($root.'/storage/keys',0700,true);mkdir($root.'/storage/sessions',0700,true);copy($source.'/.env',$root.'/.env');foreach(['private.pem','public.pem'] as $f)copy($source.'/storage/keys/'.$f,$root.'/storage/keys/'.$f);file_put_contents($root.'/storage/user-data','keep-me');return $root;}
function releaseFor(string $dir):array {$m=json_decode(file_get_contents($dir.'/update-manifest.json'),true);$id=str_repeat('a',64);$base=Remote::ORIGIN.'/api/v1/projects/open52okp/releases/'.$id;$r=['format'=>1,'id'=>$id,'project'=>'open52okp','product'=>'open52okp','channel'=>'stable','status'=>'published','verification'=>'github-sha256','version'=>$m['version'],'from'=>$m['from'],'notes'=>$m['notes'],'size'=>filesize($dir.'/open52okp-update.zip'),'sha256'=>hash_file('sha256',$dir.'/open52okp-update.zip'),'download_url'=>$base.'/package','manifest_url'=>$base.'/manifest'];foreach(['open52okp-update.zip'=>'package','update-manifest.json'=>'manifest'] as $file=>$part)$r['assets'][$file]=['size'=>filesize($dir.'/'.$file),'sha256'=>hash_file('sha256',$dir.'/'.$file),'url'=>$base.'/'.$part];return $r;}
function remoteFor(string $dir,?array $r=null):Remote {$r??=releaseFor($dir);return new Remote('open52okp',str_repeat('b',64),function($url,$dest,$limit,$progress)use($dir,$r){if(str_contains($url,'/updates?'))$body=json_encode(['api_version'=>1,'project'=>'open52okp','channel'=>'stable','current_version'=>'1.0.1','update_available'=>true,'release'=>$r]);elseif(str_ends_with($url,'/manifest'))$body=file_get_contents($dir.'/update-manifest.json');elseif(str_ends_with($url,'/package'))$body=file_get_contents($dir.'/open52okp-update.zip');else $body=json_encode($r);file_put_contents($dest,$body);if($progress)$progress(strlen($body));});}
$r=releaseFor($fixture);$remote=remoteFor($fixture);$checked=$remote->check('1.0.1');assertUpdate($checked['available']&&$checked['compatible'],'v1 query contract and exact from version');
$bad=$r;$bad['download_url']='https://evil.example/package';denied(fn()=>$remote->release($bad),'foreign download origin rejected');$bad=$r;$bad['project']='other';denied(fn()=>$remote->release($bad),'wrong project rejected');$bad=$r;$bad['status']='draft';denied(fn()=>$remote->release($bad),'draft release rejected');$bad=$r;$bad['verification']='legacy-local';denied(fn()=>$remote->release($bad),'unverified source rejected');
$root=makeRoot('success');$engine=new Engine($root);$before=hash_file('sha256',$root.'/.env');$key=hash_file('sha256',$root.'/storage/keys/private.pem');$engine->enqueue($r);denied(fn()=>$engine->enqueue($r),'duplicate install submission rejected');$engine->work($remote);$state=$engine->state();assertUpdate($state['phase']==='complete','download verify backup install and real subprocess health succeed: '.$state['message']);assertUpdate($engine->identity()['version']==='1.0.2','installed version changed');assertUpdate(hash_file('sha256',$root.'/.env')===$before&&hash_file('sha256',$root.'/storage/keys/private.pem')===$key&&file_get_contents($root.'/storage/user-data')==='keep-me','configuration signing key and runtime data preserved');assertUpdate(!is_file($root.'/storage/update-maintenance'),'maintenance cleared only after health succeeds');assertUpdate(is_file($root.'/storage/updates/'.$state['id'].'/backup/bootstrap.php'),'old code backup retained');
$root=makeRoot('health-failure');$engine=new Engine($root);$engine->enqueue($r);$calls=0;$engine->work($remote,function()use(&$calls){if(++$calls===1)throw new RuntimeException('Injected health failure');});assertUpdate($engine->state()['phase']==='rolled_back'&&$engine->identity()['version']==='1.0.1','failed health restores old version');assertUpdate(!is_file($root.'/storage/update-maintenance'),'healthy rollback leaves maintenance');
$root=makeRoot('download-failure');$engine=new Engine($root);$engine->enqueue($r);$badRemote=new Remote('open52okp',str_repeat('b',64),function(){throw new RuntimeException('Injected timeout');});$engine->work($badRemote);assertUpdate($engine->state()['phase']==='failed'&&$engine->identity()['version']==='1.0.1','download failure never modifies current code');
$root=makeRoot('terminated');$engine=new Engine($root);$engine->enqueue($r);
$helper=$workspace.'/kill-worker.php';file_put_contents($helper,'<?php require '.var_export($source.'/vendor/autoload.php',true).';require '.var_export(__DIR__.'/updates-fixture.php',true).';$e=new \\Okp\\Update\\Engine($argv[1]);$e->work(fixtureRemote($argv[2]),function(){exit(77);});');
$proc=proc_open([PHP_BINARY,'-d','extension=sodium',$helper,$root,$fixture],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);$output=stream_get_contents($pipes[1]);$error=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($proc);assertUpdate($exit===77&&$engine->state()['phase']==='health'&&is_file($root.'/storage/update-maintenance'),'terminated worker keeps journal and maintenance');file_put_contents($root.'/bootstrap.php','<?php this is intentionally broken');$recovery=proc_open([PHP_BINARY,'-d','extension=sodium',$root.'/bin/update-worker.php'],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$recoveryPipes);fclose($recoveryPipes[0]);stream_get_contents($recoveryPipes[1]);stream_get_contents($recoveryPipes[2]);fclose($recoveryPipes[1]);fclose($recoveryPipes[2]);$recoveryExit=proc_close($recovery);assertUpdate($recoveryExit===0,'standalone recovery worker runs with broken application bootstrap');assertUpdate($engine->state()['phase']==='rolled_back' &&$engine->identity()['version']==='1.0.1','next worker recovers interrupted install without network');
// Package validator adversarial fixtures, with hashes recalculated to ensure ZIP safety is checked independently.
$manifest=json_decode(file_get_contents($fixture.'/update-manifest.json'),true);$root=makeRoot('validation');$m=$manifest;$m['from']='0.9.0';denied(fn()=>Package::unpack($fixture.'/open52okp-update.zip',$workspace.'/bad-from',$m,$root,'open52okp','1.0.1'),'wrong starting version rejected');$m=$manifest;$m['php_min']='99.0.0';denied(fn()=>Package::unpack($fixture.'/open52okp-update.zip',$workspace.'/bad-runtime',$m,$root,'open52okp','1.0.1'),'incompatible PHP rejected');$m=$manifest;$m['migrations']=['unsafe'];denied(fn()=>Package::unpack($fixture.'/open52okp-update.zip',$workspace.'/bad-db',$m,$root,'open52okp','1.0.1'),'database migration rejected');
foreach(['../escape.php','.env','storage/keys/private.pem','public/uploads/payload.php','app/../escape.php','app\\bad.php','/absolute.php','app/CON.php'] as $path)assertUpdate(!Package::allowed($path),'unsafe or persistent path rejected: '.$path);
$badZip=$workspace.'/traversal.zip';copy($fixture.'/open52okp-update.zip',$badZip);$z=new ZipArchive();$z->open($badZip);$z->addFromString('../escape.php','bad');$z->close();$m=$manifest;$m['files']['../escape.php']=hash('sha256','bad');denied(fn()=>Package::unpack($badZip,$workspace.'/bad-path',$m,$root,'open52okp','1.0.1'),'traversal ZIP rejected before extraction');assertUpdate(!is_file($workspace.'/escape.php'),'ZIP traversal created no escaped file');
$m=$manifest;$m['files']['app/Application.php']=str_repeat('0',64);denied(fn()=>Package::unpack($fixture.'/open52okp-update.zip',$workspace.'/bad-hash',$m,$root,'open52okp','1.0.1'),'inner file hash mismatch rejected');
$bad=$r;$bad['assets']['update-manifest.json']['sha256']=str_repeat('0',64);$dir=$workspace.'/bad-outer';mkdir($dir);denied(fn()=>remoteFor($fixture,$bad)->download($bad,$dir),'manifest outer hash mismatch rejected');
$bad=$r;$bad['size']=$bad['assets']['open52okp-update.zip']['size']=209715201;denied(fn()=>$remote->release($bad),'oversized package metadata rejected');
$bad=$r;$bad['sha256']=$bad['assets']['open52okp-update.zip']['sha256']=str_repeat('0',64);$dir=$workspace.'/bad-zip-outer';mkdir($dir);denied(fn()=>remoteFor($fixture,$bad)->download($bad,$dir),'ZIP outer hash mismatch rejected');
foreach(['link','bomb','version'] as $kind){$path=$workspace.'/'.$kind.'.zip';copy($fixture.'/open52okp-update.zip',$path);$z=new ZipArchive();$z->open($path);$m=$manifest;if($kind==='version'){$name='update-version.json';$body=json_encode(['product'=>'open52okp','version'=>'9.9.9']);}else{$name='app/'.$kind.'.txt';$body=$kind==='bomb'?str_repeat('x',2097152):'../../.env';}$z->addFromString($name,$body);if($kind==='link')$z->setExternalAttributesName($name,ZipArchive::OPSYS_UNIX,0120777<<16);$z->close();$m['files'][$name]=hash('sha256',$body);denied(fn()=>Package::unpack($path,$workspace.'/bad-'.$kind,$m,$root,'open52okp','1.0.1'),'malicious ZIP rejected: '.$kind);}
echo "Completed: $count updater assertions. Workspace retained outside project: ".basename($workspace)."\n";
