<?php
declare(strict_types=1);
$a=require dirname(__DIR__).'/bootstrap.php';if($a->config->production()||!str_ends_with($a->config->values['db']['database'],'_test'))throw new RuntimeException('Dedicated test database required');
$d=json_decode(stream_get_contents(STDIN),true,32,JSON_THROW_ON_ERROR);$action=$d['action'];$r=(new Slim\Psr7\Factory\ServerRequestFactory())->createServerRequest('POST','http://127.0.0.1:8808/')->withHeader('Content-Type','application/x-www-form-urlencoded');
if($action==='seed'){$tag=Okp\Crypto::random(6);$password='T3st-'.Okp\Crypto::random(16);$u=$a->users->create('http-'.$tag.'@example.test',$password,'HTTP 测试');$a->db->run("UPDATE users SET role='admin' WHERE id=?",[$u['id']]);echo json_encode(['email'=>$u['email'],'password'=>$password,'id'=>$u['id']]);}
elseif($action==='email'){$a->browser->start();session_write_close();session_id($d['session']);$a->browser->start();$id=Okp\Crypto::random(16);$code=str_pad((string)random_int(0,999999),6,'0',STR_PAD_LEFT);$a->db->run('INSERT INTO email_codes(id,purpose,email,browser_hash,code_hash,expires_at) VALUES(?,?,?,?,?,?)',[$id,$d['purpose'],$d['email'],$a->browser->binding(),$a->crypto->hash($id.':'.$code),time()+300]);$_SESSION['email_codes'][$d['purpose']]=$id;session_write_close();echo json_encode(['code'=>$code]);}
elseif($action==='totp-code'){echo json_encode(['code'=>OTPHP\TOTP::createFromSecret($d['secret'])->now()]);}
elseif($action==='expire'){$a->db->run('UPDATE login_requests SET expires_at=? WHERE id=?',[time()-1,$d['ticket']]);echo '{}';}
elseif($action==='otp'){$u=$a->users->byId($d['id']);echo json_encode(['code'=>OTPHP\TOTP::createFromSecret($a->crypto->decrypt($u['totp_secret']))->now()]);}
elseif($action==='prepare'){$u=$a->users->byId($d['id']);$client='race-'.Okp\Crypto::random(6);$secret=Okp\Crypto::random();$a->db->run('INSERT INTO clients(id,name,secret_hash,confidential,redirect_uris,logout_uris,created_at) VALUES(?,?,?,1,?,?,?)',[$client,'并发测试',password_hash($secret,PASSWORD_BCRYPT),json_encode(['https://example.test/callback']),'[]',time()]);$verifier=Okp\Crypto::b64(random_bytes(48));$q=['client_id'=>$client,'redirect_uri'=>'https://example.test/callback','response_type'=>'code','scope'=>'openid','state'=>Okp\Crypto::random(16),'nonce'=>Okp\Crypto::random(16),'code_challenge'=>Okp\Crypto::b64(hash('sha256',$verifier,true)),'code_challenge_method'=>'S256'];$response=$a->oauth()->complete($q,$u['id'],$r);parse_str(parse_url($response->getHeaderLine('Location'),PHP_URL_QUERY),$parts);echo json_encode(['grant_type'=>'authorization_code','client_id'=>$client,'client_secret'=>$secret,'code'=>$parts['code'],'redirect_uri'=>$q['redirect_uri'],'code_verifier'=>$verifier]);}
elseif($action==='exchange'){$response=$a->oauth()->token($r->withParsedBody($d['data']));echo json_encode(['status'=>$response->getStatusCode(),'body'=>json_decode((string)$response->getBody(),true)]);}
elseif($action==='wechat-enable'){$a->settings->put('test-wechat-backup',$a->settings->get('wechat'));$a->settings->put('wechat',['enabled'=>true,'app_id'=>'wx4ec45155a93041cc','secret'=>'isolated-test-only','page'=>'pages/account-confirm/index','env'=>'release']);echo '{}';}
elseif($action==='wechat-restore'){$a->settings->put('wechat',$a->settings->get('test-wechat-backup'));echo '{}';}
elseif($action==='wechat-confirm'){$wx=new Okp\Wechat($a->settings,$a->db,fn()=>['body'=>json_encode(['openid'=>'test-'.$d['ticket']]),'status'=>200]);$tickets=new Okp\LoginRequests($a->db,$a->crypto,$a->rate,$wx,$a->users);$tickets->confirm(['ticket'=>$d['ticket'],'code'=>'test-only','accepted'=>true,'decision'=>'confirm'],'isolated-http-test');echo '{}';}
elseif($action==='directory-evidence'){$u=$a->db->one('SELECT id FROM users WHERE email=?',[$d['email']]);echo json_encode((new Okp\AdminUsers($a->db))->details($u['id'])['member']);}
elseif($action==='wechat-user-create'){$u=$a->users->fromWechat($d['app'],$d['openid']);echo json_encode(['id'=>$u['id'],'display_name'=>$u['display_name']]);}
else throw new RuntimeException('Unknown test action');
