<?php
declare(strict_types=1);
namespace Okp;
use Psr\Http\Message\ServerRequestInterface as Request;
final class AdminController {
 public function __construct(private Application $a){}
 private function guard(bool $recent=false):array{$u=(new WebController($this->a))->requireUser(true);if($recent&&($_SESSION['user']['at']??0)<time()-300)throw new Problem('管理配置需要最近 5 分钟内验证身份，请退出后重新登录',403);return $u;}
 public function index(Request $r){$this->guard();$page=max(1,min(100000,(int)Http::query($r,'page')));$offset=($page-1)*50;$q=trim(Http::query($r,'q'));$where=$q===''?'':' WHERE email LIKE ? OR username LIKE ?';$args=$q===''?[]:['%'.$q.'%','%'.$q.'%'];return $this->a->view->render('admin',['title'=>'账号中枢管理','members'=>$this->a->db->all('SELECT id,username,email,display_name,enabled,role FROM users'.$where.' ORDER BY created_at DESC LIMIT 50 OFFSET '.$offset,$args),'clients'=>$this->a->db->all('SELECT * FROM clients ORDER BY created_at DESC LIMIT 100'),'events'=>$this->a->db->all('SELECT * FROM audit_events ORDER BY id DESC LIMIT 50'),'wx'=>$this->a->settings->get('wechat'),'smtp'=>$this->a->settings->get('smtp'),'q'=>$q,'page'=>$page]);}
 public function user(Request $r){$me=$this->guard(true);$id=Http::input($r,'id');$enabled=Http::input($r,'enabled')==='1';$this->a->db->transaction(function()use($id,$enabled,$me){$u=$this->a->users->byId($id,true);if(!$u)throw new Problem('用户不存在',404);if(!$enabled&&($u['id']===$me['id']||$u['role']==='admin'))throw new Problem('管理员账号不可在此禁用');$this->a->db->run('UPDATE users SET enabled=? WHERE id=?',[(int)$enabled,$id]);$this->a->users->revokeSessions($id);});$this->a->audit->log('admin.user-status',$id,Http::ip($r,$this->a->config),$enabled?'enabled':'disabled');return Http::redirect('/admin');}
 private function uris(string $raw,bool $required):array{$list=array_values(array_unique(array_filter(array_map('trim',preg_split('/\R/',$raw)))));if(($required&&!$list)||count($list)>10)throw new Problem('回调地址需为 1～10 个，每行一个');foreach($list as $url){$p=parse_url($url);if(!$p||!filter_var($url,FILTER_VALIDATE_URL)||isset($p['fragment'])||isset($p['user'])||isset($p['pass'])||str_contains($url,'*')||(($p['scheme']??'')!=='https'&&!(!$this->a->config->production()&&($p['scheme']??'')==='http'&&in_array($p['host']??'',['localhost','127.0.0.1'],true))))throw new Problem('回调必须为完整 HTTPS 地址，不支持通配符');parse_str($p['query']??'',$params);if(array_intersect(['code','state','error'],array_keys($params)))throw new Problem('回调地址不能预置 code/state/error 参数');}return $list;}
 public function client(Request $r){$this->guard(true);$id=Http::input($r,'id');$name=trim(Http::input($r,'name'));if(!preg_match('/^[A-Za-z0-9_.-]{3,100}$/',$id)||$name===''||mb_strlen($name)>191)throw new Problem('应用 ID 使用 3～100 位字母、数字、下划线、点或横线，名称不能为空');$redirect=$this->uris(Http::input($r,'redirect_uris'),true);$logout=$this->uris(Http::input($r,'logout_uris'),false);$private=Http::input($r,'confidential')==='1';$enabled=Http::input($r,'enabled')==='1';$old=$this->a->db->one('SELECT * FROM clients WHERE id=?',[$id]);$rotate=$private&&(!$old||!$old['confidential']||Http::input($r,'rotate')==='1');$secret=$rotate?Crypto::random():null;$hash=$private?($secret?password_hash($secret,PASSWORD_BCRYPT,['cost'=>12]):$old['secret_hash']):null;
  $this->a->db->transaction(function()use($id,$name,$hash,$private,$redirect,$logout,$enabled){$this->a->db->run('INSERT INTO clients(id,name,secret_hash,confidential,redirect_uris,logout_uris,enabled,created_at) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),secret_hash=VALUES(secret_hash),confidential=VALUES(confidential),redirect_uris=VALUES(redirect_uris),logout_uris=VALUES(logout_uris),enabled=VALUES(enabled)',[$id,$name,$hash,(int)$private,json_encode($redirect),json_encode($logout),(int)$enabled,time()]);$this->a->db->run('UPDATE access_tokens SET revoked=1 WHERE client_id=?',[$id]);$this->a->db->run('UPDATE auth_codes SET revoked=1 WHERE client_id=?',[$id]);});$this->a->audit->log('admin.client-saved',null,Http::ip($r,$this->a->config),$id);if($secret)return $this->a->view->render('client-secret',['title'=>'保存应用密钥','clientId'=>$id,'secret'=>$secret]);$this->a->browser->flash('应用配置已保存，旧凭证已撤销');return Http::redirect('/admin');
 }
 public function settings(Request $r){$this->guard(true);$kind=Http::input($r,'kind');if($kind==='wechat'){$old=$this->a->settings->get('wechat');$id=Http::input($r,'app_id');$page=Http::input($r,'page');if(!preg_match('/^wx[a-fA-F0-9]{16}$/',$id)||!preg_match('#^pages/[A-Za-z0-9_/-]+$#',$page))throw new Problem('请填写正确的小程序 AppID 和页面路径');$env=Http::input($r,'env');if(!in_array($env,['release','trial','develop'],true))throw new Problem('小程序版本无效');$value=['enabled'=>Http::input($r,'enabled')==='1','app_id'=>$id,'secret'=>Http::input($r,'secret')?:($old['secret']??''),'page'=>$page,'env'=>$env];if(!$value['secret'])throw new Problem('请填写小程序密钥');}
  elseif($kind==='smtp'){$old=$this->a->settings->get('smtp');$host=trim(Http::input($r,'host'));$port=(int)Http::input($r,'port');$security=Http::input($r,'security');if(!preg_match('/^[a-zA-Z0-9.-]+$/',$host)||$port<1||$port>65535||!in_array($security,['tls','ssl'],true))throw new Problem('邮件服务器配置无效');$value=['host'=>$host,'port'=>$port,'security'=>$security,'username'=>Http::input($r,'username'),'password'=>Http::input($r,'password')?:($old['password']??''),'from'=>Users::email(Http::input($r,'from')),'name'=>'52okp 账号中心'];}
  else throw new Problem('配置类型无效');$this->a->settings->put($kind,$value);$this->a->audit->log('admin.settings-saved',null,Http::ip($r,$this->a->config),$kind);$this->a->browser->flash('配置已加密保存');return Http::redirect('/admin');
 }
}
